// <auto-generated />
using System;
using AndyJavier_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndyJavier_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AndyJavier_AP1_P2.Models.Combos", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Vendido")
                        .HasColumnType("bit");

                    b.HasKey("ComboId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("AndyJavier_AP1_P2.Models.CombosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("ComboId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CombosDetalle");
                });

            modelBuilder.Entity("AndyJavier_AP1_P2.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 105m,
                            Descripcion = "Procesador Ryzen 5 5600X",
                            Existencia = 8,
                            Precio = 300m
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 82m,
                            Descripcion = "RAM Corsair DDR4 2x16 GB",
                            Existencia = 10,
                            Precio = 200m
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 100m,
                            Descripcion = "Almacenamiento NVME4.0 1TB Samsung",
                            Existencia = 15,
                            Precio = 200m
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 305m,
                            Descripcion = "Grafica NVIDIA RTX 4060",
                            Existencia = 3,
                            Precio = 500m
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 160m,
                            Descripcion = "Case Lian Li Black",
                            Existencia = 4,
                            Precio = 280m
                        },
                        new
                        {
                            ProductoId = 6,
                            Costo = 60m,
                            Descripcion = "Mouse Razer",
                            Existencia = 28,
                            Precio = 100m
                        },
                        new
                        {
                            ProductoId = 7,
                            Costo = 115m,
                            Descripcion = "Power Supply Redragon 850W 80+G",
                            Existencia = 5,
                            Precio = 280m
                        },
                        new
                        {
                            ProductoId = 8,
                            Costo = 160m,
                            Descripcion = "Motherboard Asus Strix B550F",
                            Existencia = 4,
                            Precio = 300m
                        },
                        new
                        {
                            ProductoId = 9,
                            Costo = 110m,
                            Descripcion = "Monitor Acer 24p IPS 1080 180hz",
                            Existencia = 2,
                            Precio = 250m
                        },
                        new
                        {
                            ProductoId = 10,
                            Costo = 60m,
                            Descripcion = "Teclado Redragon RGB 60% Blue Switches",
                            Existencia = 8,
                            Precio = 100m
                        });
                });

            modelBuilder.Entity("AndyJavier_AP1_P2.Models.CombosDetalle", b =>
                {
                    b.HasOne("AndyJavier_AP1_P2.Models.Combos", "Combo")
                        .WithMany("CombosDetalles")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndyJavier_AP1_P2.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AndyJavier_AP1_P2.Models.Combos", b =>
                {
                    b.Navigation("CombosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
